### ISSUE TITLE
Problem delayed delivery and 

### ISSUE THREAD

**Issue by sandernaert** [MassTransit/Sample-AzureFunction#10]
I'm having issues setting up MassTransit with Azure Functions V4 running out of process. 

I want to setup the error handling for my messages. My goal is to have some delayed redeliveries and if it still fails I expect it to go to the ..._error queue. Delayed redelivery works but it also logs an exception **System.InvalidOperationException: The ConsumeContext was already set.**
At the last retry this errors bubbles up into my function and the message isn't send to the error queue.

I forked the sample repo with my tests. My configuration is minimal. Is there anything I do wrong, that causes this? 

```
[2022-09-29T08:04:25.621Z] Executing 'Functions.SubmitOrder' (Reason='(null)', Id=1c0bb8e7-ea55-4001-90d8-3e94a5eb7e93)
[2022-09-29T08:04:25.625Z] Trigger Details: MessageId: bc6c00005dc40015d59708daa1f055cd, SequenceNumber: 24, DeliveryCount: 1, EnqueuedTimeUtc: 2022-09-29T08:04:26.4110000Z, LockedUntilUtc: 2022-09-29T08:04:56.4110000Z, SessionId: (null)
[2022-09-29T08:04:29.394Z] info: MassTransit[0]
[2022-09-29T08:04:29.396Z]       Processing SubmitOrder: ORDER1
[2022-09-29T08:04:29.396Z] Processing SubmitOrder: ORDER1
[2022-09-29T08:04:29.430Z] warn: MassTransit[0]
[2022-09-29T08:04:29.433Z]       R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
[2022-09-29T08:04:29.452Z] R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
[2022-09-29T08:04:29.457Z] Result: R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
Exception: System.Exception: TESTING ERROR HANDLING
[2022-09-29T08:04:29.454Z]       System.Exception: TESTING ERROR HANDLING
[2022-09-29T08:04:29.459Z]    at Sample.AzureFunction.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\Users\Sander\source\repos\Sample-AzureFunction\src\Sample.AzureFunction\Consumers\SubmitOrderConsumer.cs:line 21
[2022-09-29T08:04:29.474Z]    at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.476Z]    at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.479Z]    at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 46
[2022-09-29T08:04:29.481Z]    at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 64
[2022-09-29T08:04:29.482Z]    at MassTransit.Middleware.RetryFilter`1.MassTransit.IFilter<TContext>.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/RetryFilter.cs:line 47
Stack:    at Sample.AzureFunction.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\Users\Sander\source\repos\Sample-AzureFunction\src\Sample.AzureFunction\Consumers\SubmitOrderConsumer.cs:line 21
[2022-09-29T08:04:29.484Z]    at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.485Z]    at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.487Z]    at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 46
[2022-09-29T08:04:29.488Z]    at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 64
[2022-09-29T08:04:29.489Z]    at MassTransit.Middleware.RetryFilter`1.MassTransit.IFilter<TContext>.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/RetryFilter.cs:line 47.
[2022-09-29T08:04:29.460Z]          at Sample.AzureFunction.Consumers.SubmitOrderConsumer.Consume(ConsumeContext`1 context) in C:\Users\Sander\source\repos\Sample-AzureFunction\src\Sample.AzureFunction\Consumers\SubmitOrderConsumer.cs:line 21
[2022-09-29T08:04:29.498Z]          at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.500Z]          at MassTransit.DependencyInjection.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/DependencyInjection/DependencyInjection/ScopeConsumerFactory.cs:line 22
[2022-09-29T08:04:29.502Z]          at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 46
[2022-09-29T08:04:29.503Z]          at MassTransit.Middleware.ConsumerMessageFilter`2.MassTransit.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumerMessageFilter.cs:line 64
[2022-09-29T08:04:29.504Z]          at MassTransit.Middleware.RetryFilter`1.MassTransit.IFilter<TContext>.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/RetryFilter.cs:line 47
[2022-09-29T08:04:31.086Z] warn: MassTransit[0]
[2022-09-29T08:04:31.089Z]       R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
[2022-09-29T08:04:31.091Z] R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
[2022-09-29T08:04:31.094Z]       System.InvalidOperationException: The ConsumeContext was already set.
[2022-09-29T08:04:31.097Z] Result: R-RETRY sb://name.servicebus.windows.net/submit-order bc6c0000-5dc4-0015-d597-08daa1f055cd MassTransit.RetryPolicies.RetryConsumeContext<Sample.AzureFunction.SubmitOrder>
Exception: System.InvalidOperationException: The ConsumeContext was already set.
````

[https://github.com/sandernaert/Sample-AzureFunction/tree/redelivery](url)

Logs: [https://github.com/sandernaert/Sample-AzureFunction/blob/redelivery/logs.txt](url)

**Comment by phatboyg** [comment]
Delayed redelivery is not supported when MassTransit isn't the transport.
